name: "exec-user"
shortDesc: "Exec user plugin"
longDesc: >
  Exec as a specified user into a container.
example: ""
command: "./exec-user.sh"
flags:
  - name: "targetuser"
    shorthand: "u"
    desc: "Username or UID. If omitted, will use root"
    defValue: "root"
  - name: "container"
    shorthand: "c"
    desc: "Container name. If omitted, the first container in the pod will be chosen"
  - name: "name"
    shorthand: "o"
    desc: "Name for new exec-user pod. If omitted it will use exec-user + $POD"
